runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

resources:
  memory_gb: 4

manual_scaling:
  instances: 1

handlers:
- url: .*
  secure: always
  redirect_http_response_code: 301
  script: auto